export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith('/api/')) return env.ASSETS.fetch(request);
    const cors = {'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization'};
    if (request.method === 'OPTIONS') return new Response(null,{headers:cors});
    let body={};try{const ct=request.headers.get('Content-Type')||'';if(ct.includes('application/json'))body=await request.json()}catch(e){}
    const ip=request.headers.get('CF-Connecting-IP')||'';const dev=request.headers.get('User-Agent')||'';
    const gU=async()=>{const a=request.headers.get('Authorization');if(!a||!a.startsWith('Bearer '))return null;const s=await env.DB.prepare('SELECT username FROM sessions WHERE token=***').bind(a.slice(7)).first();return s?s.username:null};
    const iA=async(u)=>{if(!u)return false;const r=await env.DB.prepare('SELECT role FROM users WHERE username=?').bind(u).first();return r&&r.role==='admin'};
    const adL=async(u,a,d)=>{await env.DB.prepare('INSERT INTO audit_logs(username,action,detail,ip,device) VALUES(?,?,?,?,?)').bind(u,a,d||'',ip,dev).run()};
    const j=(d,s)=>{return new Response(JSON.stringify(d),{status:s||200,headers:{'Content-Type':'application/json',...cors}})};
    try{
      if(url.pathname==='/api/register'&&request.method==='POST'){const{username,password}=body;if(!username||!password||username.length<3)return j({error:'至少3字符'},400);const e=await env.DB.prepare('SELECT username FROM users WHERE username=?').bind(username).first();if(e)return j({error:'已存在'},409);await env.DB.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,\'user\')').bind(username,password).run();await adL(username,'register','注册');return j({success:true})}
      if(url.pathname==='/api/login'&&request.method==='POST'){const{username,password}=body;if(!username||!password)return j({error:'请输入'},400);const u=await env.DB.prepare('SELECT username,password_hash,role FROM users WHERE username=?').bind(username).first();if(!u||u.password_hash!==password)return j({error:'用户名或密码错误'},401);let t='';for(let i=0;i<32;i++)t+='abcdefghijklmnopqrstuvwxyz0123456789'.charAt(Math.floor(Math.random()*36));await env.DB.prepare('INSERT INTO sessions(token,username) VALUES(?,?)').bind(t,username).run();await adL(username,u.role==='admin'?'admin':'login',u.role==='admin'?'管理员登录':'登录');return j({success:true,token:t,username:u.username,role:u.role})}
      if(url.pathname==='/api/logout'&&request.method==='POST'){const a=request.headers.get('Authorization');if(a&&a.startsWith('Bearer '))await env.DB.prepare('DELETE FROM sessions WHERE token=***').bind(a.slice(7)).run();return j({success:true})}
      if(url.pathname==='/api/me'&&request.method==='GET'){const u=await gU();if(!u)return j({user:null});const r=await env.DB.prepare('SELECT username,role FROM users WHERE username=?').bind(u).first();return j({user:r?{username:r.username,role:r.role}:null})}
      if(url.pathname==='/api/admin/stats'&&request.method==='GET'){const u=await gU();if(!u||!(await iA(u)))return j({error:'无权限'},403);const uc=(await env.DB.prepare('SELECT COUNT(*) as c FROM users').first()).c;const lc=(await env.DB.prepare("SELECT COUNT(*) as c FROM audit_logs WHERE created_at>=datetime('now','-1 day')").first()).c;const t=await env.DB.prepare("SELECT COALESCE(bytes,0) as b FROM traffic WHERE date=date('now')").first();return j({totalUsers:uc,recentLogins:lc,trafficToday:(t&&t.b)||0})}
      if(url.pathname==='/api/admin/users'&&request.method==='GET'){const u=await gU();if(!u||!(await iA(u)))return j({error:'无权限'},403);const{results}=await env.DB.prepare('SELECT username,password_hash as password,role FROM users ORDER BY created_at DESC').all();return j({users:results})}
      if(url.pathname.startsWith('/api/admin/users/')&&request.method==='PUT'){const a=await gU();if(!a||!(await iA(a)))return j({error:'无权限'},403);const tu=decodeURIComponent(url.pathname.replace('/api/admin/users/',''));const{password,role}=body;if(tu==='admin'&&role!=='admin')return j({error:'管理员角色不可变更'},400);await env.DB.prepare('UPDATE users SET password_hash=?,role=? WHERE username=?').bind(password,role,tu).run();await adL(a,'update','修改: '+tu);return j({success:true})}
      if(url.pathname.startsWith('/api/admin/users/')&&request.method==='DELETE'){const a=await gU();if(!a||!(await iA(a)))return j({error:'无权限'},403);const tu=decodeURIComponent(url.pathname.replace('/api/admin/users/',''));if(tu==='admin')return j({error:'不能删除管理员'},400);await env.DB.prepare('DELETE FROM users WHERE username=?').bind(tu).run();await env.DB.prepare('DELETE FROM sessions WHERE username=?').bind(tu).run();await adL(a,'delete','删除: '+tu);return j({success:true})}
      if(url.pathname==='/api/admin/logs'&&request.method==='GET'){const u=await gU();if(!u||!(await iA(u)))return j({error:'无权限'},403);const f=url.searchParams.get('filter')||'all';let q=[];if(f==='all'){q=['SELECT * FROM audit_logs ORDER BY id DESC LIMIT 200',[]]}else{q=['SELECT * FROM audit_logs WHERE action=? ORDER BY id DESC LIMIT 200',[f]]}const{results}=await env.DB.prepare(q[0]).bind(...q[1]).all();return j({logs:results})}
      if(url.pathname==='/api/admin/logs'&&request.method==='DELETE'){const u=await gU();if(!u||!(await iA(u)))return j({error:'无权限'},403);await env.DB.prepare('DELETE FROM audit_logs').run();return j({success:true})}
      if(url.pathname==='/api/track'&&request.method==='POST'){if(body.bytes){await env.DB.prepare("INSERT INTO traffic(date,bytes) VALUES(date('now'),?) ON CONFLICT(date) DO UPDATE SET bytes=bytes+?").bind(body.bytes,body.bytes).run()}return j({success:true})}
      return j({error:'Not found'},404);
    }catch(e){console.error(e);return j({error:'服务器错误: '+e.message},500)}
  }
};
